import Foundation

public enum SwiftEmitter {
    public static func generate(_ document: TokenDocument) throws -> String {
        try document.validate()
        var lines: [String] = [
            "// Generated by Skyfig. Do not edit.",
            "// Source of truth: Tokens/skyfig.tokens.json",
            "",
            "import Foundation",
            "",
            "public enum SkyfigTokens {",
        ]

        lines += renderCategory("Colors", declarations: document.tokens.colors.mapValues { token in
            colorExpression(light: token.values["light"]!, dark: token.values["dark"]!)
        }, indent: 1)
        lines += renderCategory("Typography", declarations: document.tokens.typography.mapValues { token in
            let value = token.value
            return "SkyfigTypographyToken(fontFamily: \(swiftString(value.fontFamily)), fontSize: \(number(value.fontSize)), fontWeight: .\(weightName(value.fontWeight)), lineHeight: \(number(value.lineHeight)), letterSpacing: \(number(value.letterSpacing)))"
        }, indent: 1)
        lines += renderCategory("Spacing", declarations: document.tokens.spacing.mapValues { number($0.value) }, type: "Double", indent: 1)
        lines += renderCategory("CornerRadii", declarations: document.tokens.cornerRadii.mapValues { number($0.value) }, type: "Double", indent: 1)
        lines += renderCategory("BorderWidths", declarations: document.tokens.borderWidths.mapValues { number($0.value) }, type: "Double", indent: 1)
        lines += renderCategory("Shadows", declarations: document.tokens.shadows.mapValues(shadowExpression), indent: 1)
        lines.append("}")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    public static func write(_ document: TokenDocument, to url: URL, check: Bool = false) throws {
        let generated = Data(try generate(document).utf8)
        let existing = try? Data(contentsOf: url)
        if check {
            guard existing == generated else { throw GeneratorError.staleOutput(url.path) }
            return
        }
        guard existing != generated else { return }
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try generated.write(to: url, options: .atomic)
    }
}

public enum GeneratorError: Error, CustomStringConvertible, Equatable {
    case invalidColor(String)
    case staleOutput(String)

    public var description: String {
        switch self {
        case .invalidColor(let value): "Invalid canonical color: \(value)"
        case .staleOutput(let path): "Generated output is stale: \(path)"
        }
    }
}

private final class Namespace {
    var leaves: [String: String] = [:]
    var children: [String: Namespace] = [:]

    func insert(path: String, declaration: String) {
        let parts = path.split(separator: ".").map(String.init)
        var node = self
        for part in parts.dropLast() {
            if node.children[part] == nil { node.children[part] = Namespace() }
            node = node.children[part]!
        }
        node.leaves[parts.last!] = declaration
    }
}

private func renderCategory(
    _ name: String,
    declarations: [String: String],
    type: String? = nil,
    indent: Int
) -> [String] {
    let root = Namespace()
    for key in declarations.keys.sorted() {
        root.insert(path: key, declaration: declarations[key]!)
    }
    let prefix = String(repeating: "    ", count: indent)
    var lines = ["\(prefix)public enum \(name) {"]
    lines += render(root, valueType: type, indent: indent + 1)
    lines.append("\(prefix)}")
    return lines
}

private func render(_ node: Namespace, valueType: String?, indent: Int) -> [String] {
    let prefix = String(repeating: "    ", count: indent)
    var lines: [String] = []
    for name in node.leaves.keys.sorted() {
        let annotation = valueType.map { ": \($0)" } ?? ""
        lines.append("\(prefix)public static let \(swiftIdentifier(name))\(annotation) = \(node.leaves[name]!)")
    }
    for name in node.children.keys.sorted() {
        lines.append("\(prefix)public enum \(typeIdentifier(name)) {")
        lines += render(node.children[name]!, valueType: valueType, indent: indent + 1)
        lines.append("\(prefix)}")
    }
    return lines
}

private func colorExpression(light: String, dark: String) -> String {
    "SkyfigColorToken(light: \(rgbaExpression(light)), dark: \(rgbaExpression(dark)))"
}

private func shadowExpression(_ token: ShadowToken) -> String {
    let layers = token.value.map { layer in
        "SkyfigShadowLayer(kind: .\(layer.kind.rawValue), color: \(colorExpression(light: layer.color["light"]!, dark: layer.color["dark"]!)), x: \(number(layer.x)), y: \(number(layer.y)), blur: \(number(layer.blur)), spread: \(number(layer.spread)))"
    }.joined(separator: ", ")
    return "SkyfigShadowToken(layers: [\(layers)])"
}

private func rgbaExpression(_ hex: String) -> String {
    let value = String(hex.dropFirst())
    let components = stride(from: 0, to: 8, by: 2).map { offset -> UInt8 in
        let start = value.index(value.startIndex, offsetBy: offset)
        let end = value.index(start, offsetBy: 2)
        return UInt8(value[start..<end], radix: 16)!
    }
    return "SkyfigRGBAColor(red: \(components[0]), green: \(components[1]), blue: \(components[2]), alpha: \(components[3]))"
}

private func weightName(_ weight: Int) -> String {
    switch weight {
    case 100: "ultraLight"
    case 200: "thin"
    case 300: "light"
    case 400: "regular"
    case 500: "medium"
    case 600: "semibold"
    case 700: "bold"
    case 800: "heavy"
    case 900: "black"
    default: "regular"
    }
}

private func number(_ value: Double) -> String {
    if value == 0 { return "0" }
    let text = String(value)
    return text.hasSuffix(".0") ? String(text.dropLast(2)) : text
}

private func swiftString(_ value: String) -> String {
    var escaped = ""
    for scalar in value.unicodeScalars {
        switch scalar.value {
        case 0x22: escaped += "\\\""
        case 0x5C: escaped += "\\\\"
        case 0x0A: escaped += "\\n"
        case 0x0D: escaped += "\\r"
        case 0x09: escaped += "\\t"
        case 0x00...0x1F, 0x7F, 0x2028, 0x2029:
            escaped += "\\u{\(String(scalar.value, radix: 16, uppercase: true))}"
        default:
            escaped.unicodeScalars.append(scalar)
        }
    }
    return "\"\(escaped)\""
}

private func typeIdentifier(_ value: String) -> String {
    guard let first = value.first else { return value }
    return swiftIdentifier(String(first).uppercased() + value.dropFirst())
}
