import Foundation

/// Generates deterministic typed Swift source from a validated token document.
public enum SwiftEmitter {
    public static func generate(_ document: TokenDocument, namespace: String = "SkyfigTokens") throws -> String {
        try document.validate()
        try validateNamespace(namespace)
        var lines: [String] = [
            "// Generated by Skyfig. Do not edit.",
            "// Source of truth: Tokens/skyfig.tokens.json",
            "",
            "import Foundation",
            "",
            "public enum \(namespace) {",
        ]

        lines += renderCategory("Colors", declarations: document.tokens.colors.mapValues { token in
            colorExpression(light: token.values["light"]!, dark: token.values["dark"]!)
        }, indent: 1)
        lines += renderCategory(
            "Typography",
            declarations: document.tokens.typography.mapValues { token in
                let value = token.value
                return "SkyfigTypographyToken(fontFamily: \(swiftString(value.fontFamily)), "
                    + "fontSize: \(number(value.fontSize)), fontWeight: .\(weightName(value.fontWeight)), "
                    + "lineHeight: \(number(value.lineHeight)), letterSpacing: \(number(value.letterSpacing)))"
            },
            indent: 1
        )
        lines += renderCategory(
            "Spacing", declarations: document.tokens.spacing.mapValues { number($0.value) }, type: "Double", indent: 1
        )
        lines += renderCategory(
            "CornerRadii",
            declarations: document.tokens.cornerRadii.mapValues { number($0.value) },
            type: "Double",
            indent: 1
        )
        lines += renderCategory(
            "BorderWidths",
            declarations: document.tokens.borderWidths.mapValues { number($0.value) },
            type: "Double",
            indent: 1
        )
        lines += renderCategory("Shadows", declarations: document.tokens.shadows.mapValues(shadowExpression), indent: 1)
        lines += renderCategory(
            "Metrics", declarations: document.tokens.metrics.mapValues { number($0.value) }, type: "Double", indent: 1
        )
        lines += renderCategory(
            "Opacities",
            declarations: document.tokens.opacities.mapValues { number($0.value) },
            type: "Double",
            indent: 1
        )
        lines += renderCategory(
            "Materials",
            declarations: document.tokens.materials.mapValues { "SkyfigMaterialToken(.\($0.value.rawValue))" },
            indent: 1
        )
        lines += renderCategory(
            "Symbols", declarations: document.tokens.symbols.mapValues(symbolExpression), indent: 1
        )
        lines += renderCategory(
            "Motion", declarations: document.tokens.motion.mapValues(motionExpression), indent: 1
        )
        lines += renderDynamic(document.tokens.dynamic, indent: 1)
        lines.append("}")
        if namespace != "SkyfigTokens" {
            lines.append("")
            lines.append("/// Compatibility alias retained for bundled Skyfig tests and examples.")
            lines.append("/// New application code should use \(namespace).")
            lines.append("public typealias SkyfigTokens = \(namespace)")
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }

    public static func write(
        _ document: TokenDocument,
        to url: URL,
        namespace: String = "SkyfigTokens",
        check: Bool = false
    ) throws {
        let generated = Data(try generate(document, namespace: namespace).utf8)
        let existing = try? Data(contentsOf: url)
        if check {
            guard existing == generated else { throw GeneratorError.staleOutput(url.path) }
            return
        }
        guard existing != generated else { return }
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try generated.write(to: url, options: .atomic)
    }
}

private func symbolExpression(_ token: SymbolToken) -> String {
    let availability = token.availability.map(swiftString) ?? "nil"
    return "SkyfigSymbolToken(name: \(swiftString(token.name)), "
        + "weight: .\(weightName(token.weight)), scale: .\(token.scale.rawValue), "
        + "renderingMode: .\(token.renderingMode.rawValue), tint: \(swiftString(token.tint)), "
        + "availability: \(availability))"
}

private func motionExpression(_ token: MotionToken) -> String {
    "SkyfigMotionToken(duration: \(number(token.duration)), curve: .\(token.curve.rawValue), "
        + "reduceMotionDuration: \(number(token.reduceMotionDuration)))"
}

private func renderDynamic(_ dynamic: DynamicTokenCollection, indent: Int) -> [String] {
    var declarations: [String: String] = [:]
    for (path, token) in dynamic.colors {
        declarations[path] = colorExpression(light: token.values["light"]!, dark: token.values["dark"]!)
    }
    for (path, token) in dynamic.numbers {
        declarations[path] = "SkyfigThemedValue<Double>(light: \(number(token.values["light"]!)), "
            + "dark: \(number(token.values["dark"]!)))"
    }
    for (path, token) in dynamic.strings {
        declarations[path] = "SkyfigThemedValue<String>(light: \(swiftString(token.values["light"]!)), "
            + "dark: \(swiftString(token.values["dark"]!)))"
    }
    for (path, token) in dynamic.booleans {
        declarations[path] = "SkyfigThemedValue<Bool>(light: \(token.values["light"]!), "
            + "dark: \(token.values["dark"]!))"
    }
    guard !declarations.isEmpty else { return [] }
    let root = Namespace()
    for key in declarations.keys.sorted() { root.insert(path: key, declaration: declarations[key]!) }
    return render(root, valueType: nil, indent: indent)
}

/// Errors reported while generating or checking generated Swift source.
public enum GeneratorError: Error, CustomStringConvertible, Equatable {
    case invalidColor(String)
    case invalidNamespace(String)
    case staleOutput(String)

    public var description: String {
        switch self {
        case .invalidColor(let value): "Invalid canonical color: \(value)"
        case .invalidNamespace(let value): "Invalid Swift token namespace: \(value)"
        case .staleOutput(let path): "Generated output is stale: \(path)"
        }
    }
}

private func validateNamespace(_ namespace: String) throws {
    let keywords: Set<String> = [
        "actor", "associatedtype", "class", "deinit", "enum", "extension", "func", "import", "init",
        "inout", "let", "operator", "precedencegroup", "protocol", "struct", "subscript", "typealias",
        "var", "break", "case", "catch", "continue", "default", "defer", "do", "else", "fallthrough",
        "for", "guard", "if", "in", "repeat", "return", "switch", "throw", "throws", "try", "while",
        "as", "any", "false", "is", "nil", "self", "Self", "super", "true", "where"
    ]
    let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "_"))
    guard let first = namespace.unicodeScalars.first,
          CharacterSet.letters.union(CharacterSet(charactersIn: "_")).contains(first),
          namespace.unicodeScalars.allSatisfy({ allowed.contains($0) }),
          !keywords.contains(namespace) else {
        throw GeneratorError.invalidNamespace(namespace)
    }
}

private final class Namespace {
    var leaves: [String: String] = [:]
    var children: [String: Namespace] = [:]

    func insert(path: String, declaration: String) {
        let parts = path.split(separator: ".").map(String.init)
        var node = self
        for part in parts.dropLast() {
            if node.children[part] == nil { node.children[part] = Namespace() }
            node = node.children[part]!
        }
        node.leaves[parts.last!] = declaration
    }
}

private func renderCategory(
    _ name: String,
    declarations: [String: String],
    type: String? = nil,
    indent: Int
) -> [String] {
    let root = Namespace()
    for key in declarations.keys.sorted() {
        root.insert(path: key, declaration: declarations[key]!)
    }
    let prefix = String(repeating: "    ", count: indent)
    var lines = ["\(prefix)public enum \(name) {"]
    lines += render(root, valueType: type, indent: indent + 1)
    lines.append("\(prefix)}")
    return lines
}

private func render(_ node: Namespace, valueType: String?, indent: Int) -> [String] {
    let prefix = String(repeating: "    ", count: indent)
    var lines: [String] = []
    for name in node.leaves.keys.sorted() {
        let annotation = valueType.map { ": \($0)" } ?? ""
        lines.append("\(prefix)public static let \(swiftIdentifier(name))\(annotation) = \(node.leaves[name]!)")
    }
    for name in node.children.keys.sorted() {
        lines.append("\(prefix)public enum \(typeIdentifier(name)) {")
        lines += render(node.children[name]!, valueType: valueType, indent: indent + 1)
        lines.append("\(prefix)}")
    }
    return lines
}

private func colorExpression(light: String, dark: String) -> String {
    "SkyfigColorToken(light: \(rgbaExpression(light)), dark: \(rgbaExpression(dark)))"
}

private func shadowExpression(_ token: ShadowToken) -> String {
    let layers = token.value.map { layer in
        let color = colorExpression(light: layer.color["light"]!, dark: layer.color["dark"]!)
        return "SkyfigShadowLayer(kind: .\(layer.kind.rawValue), color: \(color), "
            + "x: \(number(layer.x)), y: \(number(layer.y)), blur: \(number(layer.blur)), "
            + "spread: \(number(layer.spread)))"
    }.joined(separator: ", ")
    return "SkyfigShadowToken(layers: [\(layers)])"
}

private func rgbaExpression(_ hex: String) -> String {
    let value = String(hex.dropFirst())
    let components = stride(from: 0, to: 8, by: 2).map { offset -> UInt8 in
        let start = value.index(value.startIndex, offsetBy: offset)
        let end = value.index(start, offsetBy: 2)
        return UInt8(value[start..<end], radix: 16)!
    }
    return "SkyfigRGBAColor(red: \(components[0]), green: \(components[1]), blue: \(components[2]), alpha: \(components[3]))"
}

private func weightName(_ weight: Int) -> String {
    switch weight {
    case 100: "ultraLight"
    case 200: "thin"
    case 300: "light"
    case 400: "regular"
    case 500: "medium"
    case 600: "semibold"
    case 700: "bold"
    case 800: "heavy"
    case 900: "black"
    default: "regular"
    }
}

private func number(_ value: Double) -> String {
    if value == 0 { return "0" }
    let text = String(value)
    return text.hasSuffix(".0") ? String(text.dropLast(2)) : text
}

private func swiftString(_ value: String) -> String {
    var escaped = ""
    for scalar in value.unicodeScalars {
        switch scalar.value {
        case 0x22: escaped += "\\\""
        case 0x5C: escaped += "\\\\"
        case 0x0A: escaped += "\\n"
        case 0x0D: escaped += "\\r"
        case 0x09: escaped += "\\t"
        case 0x00...0x1F, 0x7F, 0x2028, 0x2029:
            escaped += "\\u{\(String(scalar.value, radix: 16, uppercase: true))}"
        default:
            escaped.unicodeScalars.append(scalar)
        }
    }
    return "\"\(escaped)\""
}

private func typeIdentifier(_ value: String) -> String {
    guard let first = value.first else { return value }
    return swiftIdentifier(String(first).uppercased() + value.dropFirst())
}
